// Asset manifest — maps data items to pre-generated audio/image paths
// Generated by scripts/pregenerate.ts
// Audio: /audio/<slug>.mp3
// Images: /images/gen/<slug>.webp

import { swar, vyanjan, words, phrases, stories, balgeet } from './gujarati';

function phraseSlug(roman: string): string {
  return roman.replace(/[^a-zA-Z0-9]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');
}

// Audio paths
export const audioPaths: Record<string, string> = {};

// Letters
for (const letter of [...swar, ...vyanjan]) {
  audioPaths[`letter-${letter.roman}`] = `/audio/letter-${letter.roman}.mp3`;
}
// Words
for (const word of words) {
  audioPaths[`word-${word.roman}`] = `/audio/word-${word.roman}.mp3`;
}
// Phrases
for (const phrase of phrases) {
  const slug = phraseSlug(phrase.roman);
  audioPaths[`phrase-${slug}`] = `/audio/phrase-${slug}.mp3`;
}
// Stories
for (const story of stories) {
  audioPaths[`story-${story.id}-title`] = `/audio/story-${story.id}-title.mp3`;
  for (let i = 0; i < story.lines.length; i++) {
    audioPaths[`story-${story.id}-line${i}`] = `/audio/story-${story.id}-line${i}.mp3`;
  }
}

// Balgeet (nursery rhymes) — title and one file per sung line
for (const song of balgeet) {
  audioPaths[`balgeet-${song.id}-title`] = `/audio/balgeet-${song.id}-title.mp3`;
  for (let i = 0; i < song.lines.length; i++) {
    audioPaths[`balgeet-${song.id}-line${i}`] = `/audio/balgeet-${song.id}-line${i}.mp3`;
  }
}

// Image paths
export const imagePaths: Record<string, string> = {};

// Letters
for (const letter of [...swar, ...vyanjan]) {
  imagePaths[`letter-${letter.roman}`] = `/images/gen/letter-${letter.roman}.webp`;
}
// Words
for (const word of words) {
  imagePaths[`word-${word.roman}`] = `/images/gen/word-${word.roman}.webp`;
}
// Phrases
for (const phrase of phrases) {
  const slug = phraseSlug(phrase.roman);
  imagePaths[`phrase-${slug}`] = `/images/gen/phrase-${slug}.webp`;
}
// Stories
for (const story of stories) {
  imagePaths[`story-${story.id}`] = `/images/gen/story-${story.id}.webp`;
  for (let i = 0; i < story.lines.length; i++) {
    imagePaths[`story-${story.id}-line${i}`] = `/images/gen/story-${story.id}-line${i}.webp`;
  }
}

// Balgeet hero art
for (const song of balgeet) {
  imagePaths[`balgeet-${song.id}`] = `/images/gen/balgeet-${song.id}.webp`;
}

// Helper: get audio path for a letter
export function getLetterAudio(roman: string): string | undefined {
  return audioPaths[`letter-${roman}`];
}

// Helper: get audio path for a word
export function getWordAudio(roman: string): string | undefined {
  return audioPaths[`word-${roman}`];
}

// Helper: get audio path for a phrase
export function getPhraseAudio(roman: string): string | undefined {
  return audioPaths[`phrase-${phraseSlug(roman)}`];
}

// Helper: get image path for a letter
export function getLetterImage(roman: string): string | undefined {
  return imagePaths[`letter-${roman}`];
}

// Helper: get image path for a word
export function getWordImage(roman: string): string | undefined {
  return imagePaths[`word-${roman}`];
}

// Helper: get image path for a phrase
export function getPhraseImage(roman: string): string | undefined {
  return imagePaths[`phrase-${phraseSlug(roman)}`];
}

// Helper: get story title audio
export function getStoryTitleAudio(storyId: string): string | undefined {
  return audioPaths[`story-${storyId}-title`];
}

// Helper: get story hero image
export function getStoryImage(storyId: string): string | undefined {
  return imagePaths[`story-${storyId}`];
}

// Helper: get story line audio
export function getStoryLineAudio(storyId: string, lineIndex: number): string | undefined {
  return audioPaths[`story-${storyId}-line${lineIndex}`];
}

// Helper: get story line image
export function getStoryLineImage(storyId: string, lineIndex: number): string | undefined {
  return imagePaths[`story-${storyId}-line${lineIndex}`];
}

// Helper: get a nursery rhyme's title audio
export function getBalgeetTitleAudio(songId: string): string | undefined {
  return audioPaths[`balgeet-${songId}-title`];
}

// Helper: get the audio for one sung line
export function getBalgeetLineAudio(songId: string, lineIndex: number): string | undefined {
  return audioPaths[`balgeet-${songId}-line${lineIndex}`];
}

// Helper: get a nursery rhyme's hero illustration
export function getBalgeetImage(songId: string): string | undefined {
  return imagePaths[`balgeet-${songId}`];
}

/* Story films ------------------------------------------------------------
 * Only some stories have a film. Listing them explicitly means the reader
 * shows a "make one" button straight away instead of mounting a <video> that
 * can only 404. Add an id here after running scripts/make-story-films.mts.
 */
export const STORY_FILMS = new Set<string>([
  'dadi-dhokla',
  'hare-tortoise',
  'hungry-cat',
  'kite-wind',
  'lion-mouse',
  'sun-moon',
]);

export function hasStoryVideo(storyId: string): boolean {
  return STORY_FILMS.has(storyId);
}

export function getStoryVideo(storyId: string): string {
  return `/videos/story-${storyId}.mp4`;
}
